### Author: Hao Hao

### a. Association Rule Mining

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
## Read Data
trans_df = pd.read_excel('transactions_by_dept.xlsx', sheet_name = 'transactions_by_dept')
trans_df.head()

                POS Txn                       Dept   ID  Sales U
0  16120100160021008773               0261:HOSIERY  250        2
1  16120100160021008773  0634:VITAMINS & HLTH AIDS  102        1
2  16120100160021008773          0879:PET SUPPLIES  158        2
3  16120100160021008773                 0973:CANDY  175        2
4  16120100160021008773               0982:SPIRITS  176        1

In [3]:
## Transform the dataset
basket = trans_df.groupby(['POS Txn', 'Dept'])['Sales U'].sum().unstack().reset_index().fillna(0).set_index('POS Txn')
basket.head()

Dept,0002:BARBER RETAIL,0009:FLORAL SERV/SUPPLIES,0012:LOCAL GIFTS/FOODS,0014:REPAIRS,0016:FINANCIAL SERVICES,0018:OTHER DIRECT SERVICE,0033:VENDING RETAIL,0056:SOUVENIR,0066:VENDING/AMUSEMENT MA,0071:BEAUTY RETAIL,...,0941:BEDDING,0961:GENERAL GROCERIES,0962:BEVERAGES,0965:PERISHABLES,0973:CANDY,0982:SPIRITS,0983:WINE,0984:BEER,0991:TOBACCO,0999:UNSCANNED ITEMS
POS Txn,,,,,,,,,,,,,,,,,,,,,
16120100160021008773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,1.0,4.0,0.0,2.0,0.0
16120100160021008774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16120100160021008775,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16120100160021008776,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16120100160021008777,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0

In [4]:
## Transform cell values (<=0 -> False, >=1 -> True)
def encode_units(x):
    if x <= 0:
        return False
    if x >= 1:
        return True

basket_sets = basket.applymap(encode_units)

basket_sets.head()

Dept,0002:BARBER RETAIL,0009:FLORAL SERV/SUPPLIES,0012:LOCAL GIFTS/FOODS,0014:REPAIRS,0016:FINANCIAL SERVICES,0018:OTHER DIRECT SERVICE,0033:VENDING RETAIL,0056:SOUVENIR,0066:VENDING/AMUSEMENT MA,0071:BEAUTY RETAIL,...,0941:BEDDING,0961:GENERAL GROCERIES,0962:BEVERAGES,0965:PERISHABLES,0973:CANDY,0982:SPIRITS,0983:WINE,0984:BEER,0991:TOBACCO,0999:UNSCANNED ITEMS
POS Txn,,,,,,,,,,,,,,,,,,,,,
16120100160021008773,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,False,True,False
16120100160021008774,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16120100160021008775,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
16120100160021008776,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
16120100160021008777,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [5]:
## Generate frequent itemsets
frequent_itemsets = apriori(basket_sets, min_support = 0.03, use_colnames = True)
frequent_itemsets

     support                                itemsets
0   0.054264                  (0072:BARBER SERVICES)
1   0.049903               (0532:AMERICAN GREETINGS)
2   0.096899                      (0597:HEALTH AIDS)
3   0.063953                      (0603:BEAUTY CARE)
4   0.072674                    (0604:PERSONAL CARE)
5   0.031492                             (0640:TOYS)
6   0.042151                         (0646:SEASONAL)
7   0.076550               (0836:HOUSEHOLD CLEANING)
8   0.048934                     (0879:PET SUPPLIES)
9   0.047965                (0961:GENERAL GROCERIES)
10  0.122578                        (0962:BEVERAGES)
11  0.133236                            (0973:CANDY)
12  0.152132                          (0982:SPIRITS)
13  0.092539                             (0983:WINE)
14  0.063953                             (0984:BEER)
15  0.089632                          (0991:TOBACCO)
16  0.031008  (0604:PERSONAL CARE, 0597:HEALTH AIDS)
17  0.032461            (0962:BEVERAGES, 0973:CANDY)
18  0.037306               (0983:WINE, 0982:SPIRITS)

In [6]:
## Decide association rules
association_rules(frequent_itemsets, metric = "confidence", min_threshold = 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(0604:PERSONAL CARE),(0597:HEALTH AIDS),0.072674,0.096899,0.031008,0.426667,4.403200,0.023966,1.575176
1,(0597:HEALTH AIDS),(0604:PERSONAL CARE),0.096899,0.072674,0.031008,0.320000,4.403200,0.023966,1.363714
2,(0962:BEVERAGES),(0973:CANDY),0.122578,0.133236,0.032461,0.264822,1.987610,0.016129,1.178985
3,(0973:CANDY),(0962:BEVERAGES),0.133236,0.122578,0.032461,0.243636,1.987610,0.016129,1.160054
4,(0983:WINE),(0982:SPIRITS),0.092539,0.152132,0.037306,0.403141,2.649948,0.023228,1.420551
5,(0982:SPIRITS),(0983:WINE),0.152132,0.092539,0.037306,0.245223,2.649948,0.023228,1.202290

### b. Business Recommendations:

1. Give joint cross-category discounts or coupons to personal care products and health aids products.
2. Pack candy with beverages as snack bundles. 

These two approaches could help customer save time finding or incentivise them to purchase frequently brought products, so that they are exposed with products which they are more possibly interested in and eventually boost sales.